### ISSUE TITLE
Unable to read FlowRepository fcs files produced from BD AccuriTM C6 Flow Cytometer 

### ISSUE THREAD

**Issue by JauntyJJS** [RGLab/flowCore#51] opened 2015-12-17 06:53 UTC
Hi,

I was trying to use flowCore to read some fcs file from BD AccuriTM C6 Flow Cytometer.
The dataset are the first 3 fcs files available in the Flow Repository 
https://flowrepository.org/experiments/4/download_ziped_files

from

https://flowrepository.org/id/FR-FCM-ZZZ4

Accuri - C6 - A01 H2O.fcs
Accuri - C6 - A02 Spherotech 8 Peak Beads.fcs
Accuri - C6 - A03 HPB - CD45 PerCP.fcs

I tried to read them and they all got the following error

Error in readFCSdata(con, offsets, txt, transformation, which.lines, scale,  : 
  The HEADER and the TEXT segment define different starting point to read the data.
In addition: Warning messages:
1: In fcs_text_parse(txt, emptyValue = emptyValue) :
  keyword: / is dropped because no value found!
2: In fcs_text_parse(txt, emptyValue = emptyValue) :
  keyword: / is dropped because no value found!

This is my sessionInfo from R

> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flowCore_1.32.2 rj_2.0.3-1     

loaded via a namespace (and not attached):
 [1] Biobase_2.26.0      BiocGenerics_0.12.1 cluster_2.0.3      
 [4] corpcor_1.6.8       DEoptimR_1.0-4      graph_1.44.1       
 [7] grid_3.1.0          lattice_0.20-33     mvtnorm_1.0-3      
[10] parallel_3.1.0      pcaPP_1.9-60        rj.gd_2.0.0-1      
[13] robustbase_0.92-5   rrcov_1.3-8         stats4_3.1.0       
[16] tools_3.1.0  

However, I was able to read the fourth file  Accuri - C6.fcs

May I know if this error occurs due to the fcs files or flowCore not installed properly or something else ?

Thank you for your help.

Regards,
Jeremy

**Comment by JauntyJJS** [comment] 2015-12-17 08:59
I tried flowCore in version 1.36.3 but the error this persist

> sessionInfo()
R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] flowCore_1.36.3 rj_2.0.3-1     

loaded via a namespace (and not attached):
 [1] Biobase_2.26.0      BiocGenerics_0.12.1 cluster_2.0.3      
 [4] corpcor_1.6.8       DEoptimR_1.0-4      graph_1.44.1       
 [7] grid_3.1.0          lattice_0.20-33     mvtnorm_1.0-3      
[10] parallel_3.1.0      pcaPP_1.9-60        Rcpp_0.12.2        
[13] rj.gd_2.0.0-1       robustbase_0.92-5   rrcov_1.3-8        
[16] stats4_3.1.0        tools_3.1.0

**Comment by gfinak** [comment] 2015-12-17 16:37
Lately, we've been coming across FCS files that don't follow the standard. We'll have to look into it if that's the case here, but it's not that flowCore is not installed properly, this is an issue with the FCS file format.

**Comment by gfinak** [comment] 2015-12-17 17:38
There's multiple issues here. I looked at one of the files. One issue is that the `#P14MaxUsefulDataChannel` keyword contains the value "1567" followed by a double delimiter "//", leading to the error you see. You need to pass emptyValue=FALSE, to get that to parse correctly. 
A second problem that arises after that, is the $DATABEGIN $ENDTEXT and $ENDDATA keywords don't match the offsets in the header. Probably annotations were added to the text segment but the keywords weren't updated to reflect the change. You could go in an edit the keywords by hand with a text editor to match the offsets in the header. I've confirmed that this makes the file readable. Whether or not the data can be trusted is a separate issue.
Cheers,
Greg

**Comment by JauntyJJS** [comment] 2015-12-18 07:58
Dear Greg,

This is interesting. I believe the file you are referring to is "Accuri - C6 - A02 Spherotech 8 Peak Beads.fcs"

The data are collected from https://flowrepository.org/id/FR-FCM-ZZZ4 in Flow Respository.
whose purpose is to test if third party software vendors (in this case flowCore) is able to read FCS files from different vendors which may not strictly follow FCS data standard but can still be read in flowjo

**Comment by JauntyJJS** [comment] 2015-12-18 08:58
May I ask if it is possible to create an R function to edit the $DATABEGIN $ENDTEXT and $ENDDATA keyword to be the same as the offsets in the header using R instead of changing it manually with a text editor before reading it using flowCore ?

**Comment by gfinak** [comment] 2015-12-18 16:13
@jspidlen Does flowRespository modify the FCS file text segment at all? Came across an example where the header and keywords disagree on the start and end of the data segment. @JauntyJJS  says they're from your group and I know you guys use flowCore, so the file was presumably readable at some point? Question is, what should be the correct behaviour if BEGINDATA and the header offsets disagree. It seems to me that's a pretty solid indicator that the file is corrupt and should throw an error. Thoughts? @mikejiang want to weigh in?

**Comment by jspidlen** [comment] 2015-12-18 18:15
Hi Greg,

1) The only time FlowRespository modifies the header is when
de-identification is selected by the user. I am using my
own DeIdentifyFCSInputStream (extends InputStream) as part of the data
upload client, and this intercepts the data as it is being sent to the
server. Each byte is either passed on, or replaced with a space character
(if the steam detects that the byte is inside a keyword value that should
be kept private). This never moves anything around in the file so all your
offset values remain the same. Also, if you guys are talking about
FR-FCM-ZZZ4, then this is a dataset that I have uploaded and I used the
files as given to me by all the different vendors and I didn't use the
de-identification feature since I wanted the files to stay exactly the way
they were given to me. And just to be really really sure, if you guys are
talking about Accuri - C6 - A02 Spherotech 8 Peak Beads.fcs, I dug out that
original file on our network drive and the md5sum
is 2da6c856cda1ed95a8aa01d8d5fb0de8, which matches the md5sum of the file
that is in FlowRepository.

2) If offset information in the FCS HEADER disagrees with what is in the
TEXT segment ($BEGINDATA etc.), then:
- If the HEADER says 0 then use what's in the TEXT segment (this is
standard compliant)
- If the HEADER says 99999999 then also use what's in the TEXT segment
(this is NOT standard compliant, but unfortunately some vendors do put
99999999 in the HEADER instead of a large value that does not fit in there)
- In any other case, I agree that the file should simply be refused with a
reasonably sensible error message explaining that these two values do not
match and that this needs to be manually fixed by the user before you can
proceed. This applies to the Accuri - C6 - A02 Spherotech 8 Peak Beads.fcs
file. You could implement some heuristics that would guess which of the two
values is more likely to be correct, but this could be potentially
dangerous. Having said that, FlowJo does read this file, and so does
FlowRepository...

Cheers,
Josef

**Comment by gfinak** [comment] 2015-12-18 18:47
Okay, so I don't think we will be implementing any tools automatically modify the databegin or endtext keywords to match the header. But @JauntyJJS, you're welcome to do so and submit a pull request.

**Comment by mikejiang** [comment] 2015-12-18 19:56
This is the header
```r
FCSversion  textstart    textend  datastart    dataend  
         3         58       2959       2960    3399976        
```
and this is from the TEXT
```r
$BEGINSTEXT/58/$ENDSTEXT/2525/$BEGINDATA/2526/$ENDDATA/3399542
```
Should we trust `header` more than `TEXT` (except for `0` or `99999999`)? Because the latter is read based on the `header` in the first place.

@jspidlen , can you elaborate more on the heuristics logic you and flowJo has been using to determine which version of these offset values to use when there are such discrepancies? 

Also, if there is risk of  erroneously reading as you mentioned, isn't it worse than simply refusing to parse? You can imagine the end users invest huge efforts to analyze these data without knowing they had the wrong data to begin with.

**Comment by SamGG** [comment] 2015-12-18 21:24
Hi,
Let me bring you an external point of view. Of course this subject sounds interesting to me because I don't understand why the same information could be set at to different places, except in the 0 or 99999999 cases.

IMHO, the reader should trust the HEADER segment and to warn about conflicting values in the TEXT segment, unless specific cases as stated by Josef. This answers Mike's remark.

Having read the data of the FCS file of interest, I noticed that the 2526 position and following consist in "#P1MaxUsefulDataChannel/423935/" and such keywords for the other channels. My guess is that this information has been added before submission either lately by the acquisition software or after acquisition by another software. In both cases, this software modified correctly the header, but seems not to care about those redundant BEGIN/END information.

An heuristic could look for the first not human readable character which would point the beginning of the data. This value could be proposed as an alternate beginning of data if an extra flag useHeuristicSegmentGuess=TRUE.

But my point of view is to use the HEADER and I guess that it is how FlowJo is working. Just change the values in the TEXT segment and see what happen... Nothing I guess.

Finally, I also checked the other Accuri files. Oddly, the Accuri - C6.fcs file does not have the added keywords nor the empty value. I really think an extra process has led to the extra keywords.

**Comment by gfinak** [comment] 2015-12-18 21:44
@SamGG I tend to disagree. The FCS standard is pretty clear, and if the header and keywords disagree, it's a pretty clear sign that there's been some funny business. Software could just as easily write an incorrect header as an incorrect keyword, and relying on the first non-human readable character could just lead to reading in corrupted data.. the reasoning is if someone's pipeline is not writing the header or text segment correctly, why assume it's writing the data correctly? It could as easily write non-readable characters to the text segment, or mangled data.

**Comment by jspidlen** [comment] 2015-12-18 22:21
FlowRepository takes the info from the HEADER in this case. I assume FlowJo
does that as well. But I tend to agree with Greg and Mike that this is a
clear indication that somebody wrongly messed around with the file and that
it therefore could be better to refuse the file altogether. FlowJo accepts
it because in their business model, pleasing the customer is worth doing
it. FlowRepository accepts it because it is still using a parser written by
Cytobank years ago (and Cytobank motivation for being a bit lenient was
likely similar to FlowJo's).

Having said that, based on my experience, if someone messes up an FCS file
like this, they generally update the offsets info in the HEADER but they
may forget to update the $BEGIN.../$END... keywords in the TEXT segment.
This is mainly true for software that was originally written for FCS 2.0
and was later incorrectly adapted to work with FCS 3.0. I have never seen
it the other way (i.e., I have never seen that the $BEGIN.../$END...
keywords were updated but the HEADER wasn't).

If one wanted to read a file like that, there are a few additional checks
that can be done minimize the risk of reading from wrong segments. There is
the obvious check that $PAR x $TOT x $PnB / 8 == the length of the DATA
segment in bytes. But that will not catch a shift. So in addition, one
could look at the values of the TIME channel; those should be generally in
an increasing order through the file. It may be good to check a few at the
beginning and a few at the end. One could also check the values of the
other channels for the first few and last few events, and "most" of those
values should be within the mean of that channel +/- say 2 standard
deviations. But this may not be 100% reliable and there is additional
effort required to write the code for all that just because someone screwed
up when creating an FCS file in the first place... (which is why I would
argue that simply refusing the file may be a valid action to take)

Cheers,
Josef

**Comment by SamGG** [comment] 2015-12-19 00:18
Being strict enforces getting clean data, but being flexible will solve everyday problems that will still be solved by FlowJo or CytoBank. Josef's experience seems to support my point of view although he does not share it.

May be could you offer a lenient option (with many red flags) that allows reading FCS with HEADER information. I think this will be better than requiring people to setup a piece of code that will change the keywords values in the TEXT or HEADER segments. Setting such a piece of software in every lab will be a waste of time and error prone. And I don't believe that every software provider will correct its software in response to their customers.

While I don't get why the same information could be at two different places, those FCS files prove that when something could go weird, it will.

Best.

**Comment by jspidlen** [comment] 2015-12-19 01:00
>
> While I don't get why the same information could be at two different
> places, those FCS files prove that when something could go weird, it will.


Back in 1984 when the FCS format was first created, nobody could imagine a
file that would be over 100 MB, and so they reserved 8 bytes in the HEADER
segment to store the offset information. In 1997, the FCS 3.0 was released.
They (ISAC) wanted to keep everything backwards compatible as much as
possible, so they kept the HEADER as is and said, "if you need to store an
offset larger than 99999999, then write 0 in the HEADER and use defined
keywords ($BEGINDATA, etc.) in the primary TEXT segment to specify the real
offset values. At that time, the vast majority of FCS files was still <100
MB and therefore, all the old software was still able to read 99.999% of
the old files. Essentially, nobody likes this design, but it is a legacy
thing that is very hard to get rid off. (I actually tried to removed this
"feature" a few months ago when discussing an upcoming version of the FCS
specification, and hit a pretty hard wall on this one... vendors are
willing to get rid of some other obscure items (like mixed endians), but
nobody is willing to make more room for segment info in the HEADER and drop
the keywords...

On a different topic, Mike, this just reminded me, there is another thing
that I was hoping to get changed in FCS, but failed to get that passed: FCS
keywords are (and have always been) case insensitive. That means that
people can create FCS files and use keywords like $BeginData instead of
$BEGINDATA, and it is perfectly legal, and you should be able to handle
that correctly. This applies to all the keywords. I am pretty sure flowCore
is not compatible with that at this point. It may not be a big deal since I
have never seen any FCS files like that, but if somebody did it, it would
be legal... This is why I tried to change keywords to be case sensitive,
but that motion wasn't supported by the rest of the ISAC data standards
task force members.

Cheers,
Josef

**Comment by SamGG** [comment] 2015-12-19 01:17
Thanks for this clear explanation. From it, I guess either the HEADER values are 0 and the right ones are in TEXT or the values are in the HEADER and the values in the TEXT should not exist. Everything else is an incorrect lecture of the specifications.
Although I do understand that standards should evolve, I notice that the delay to their real use is long. So, please don't make too frequent changes that will misleading coding people mind ;-)
Best.
.

**Comment by SamGG** [comment] 2015-12-19 13:44
Hi Greg,
Before closing this thread, could you give us a conclusion?
Thanks.

**Comment by JauntyJJS** [comment] 2015-12-19 16:15
Dear all,

Being a statistician, I apologise that I am new to flow cytometry data and need some clarification.

The reason I do not want to match the header and text regularly is because I am dealing with over 100 fcs files. If all of the files have the same problem, changing it manually is not efficient in a long run.

Based on this long thread of conversation, can I assume that the Header information is more reliable since flowjo and flow respository does the same thing ?

Also, it seems that the group is going for a prevention is better than cure approach.

Then the question comes to how does the biologist know that they are "messing" with the file 
How does a biologist prevent this header information different from text information on when the data start and end using flowjo ?
 
I am just given data from biologist and ask to read them. If I tell them the data is corrupted because of this header and keyword reason, they will ask the same question. From a biologist perspective, it is hard for them to believe that the file is corrupted since they do not have issue reading in Flowjo.

Though I think the solution may be given by someone in this thread, could someone guide me on which one will have the biologist to prevent this mistake.

Regards,
Jeremy

**Comment by gfinak** [comment] 2015-12-19 16:55
Jeremy,  in the `IO.R` file under the `/R` directory of the package, in the `readFCSdata` function you'll find some validity checks that look like this:

```
 if(realOff["datastart"] != datastart && realOff["datastart"]!= 0){
```
`realOff` are the header offsets. `datastart` and others are from the text segment.
I encourage you to modify that region (e.g. pass in an argument that can be checked and if true overwrite the text segment values with the header values prior to the validity checks). Get the code working for you, and if it remains backward compatible, submit a pull request. We may merge it, we may not, we will discuss it some more, but at least you'll have something that you can move forward with,and tell the biologist you're working with that the data may be suspect.. and you'll have a better understanding of why, having fixed the issue yourself. 
This is a nice benefit of open source code, you don't need our blessing. This fix is probably 2 minutes of work now that you know where to look. Don't let us hold you back from getting what you need to get done. 
It's totally reasonable to adapt pieces of packages to suit your needs. Package maintainers may not always feel certain changes are a good idea in general, for a variety of reasons, we are all busy with projects other than maintaining the flow code base, so our bandwidth can be limited, but we're glad to point you in the right direction to help you move forward.
And when it works as you want, and you find it useful, I do encourage you to submit a pull request.
Best
Greg

**Comment by JauntyJJS** [comment] 2015-12-20 13:10
Dear Greg,

Thank you for the input.
Sure. At least there is something that I can do to get started with. 
I will update this thread if I have any questions.
Give me some time to rewrite the code

Regards,
Jeremy

**Comment by mikejiang** [comment] 2016-01-05 18:55
The issue is addressed by adding `ignore.text.offset` flag to the API.
By default the discrepancy will be reported as the error. User then can decide to parse it by setting this flag to `TRUE` (i.e. trust `header` and ignore `TEXT`). The same message will still be reported as warning to ensure that user is fully aware of the potential risk.

**Closed by mikejiang** 2016-01-05 18:55 UTC

**Comment by SamGG** [comment] 2016-01-05 20:30
Mike, thanks for your help to add flexibility the interface.
