### ISSUE TITLE
Error in convertRawBites fror lxb file exported from xponent 4.1

### ISSUE THREAD

**Issue by odeleongt** [RGLab/flowCore#59] opened 2016-05-04 20:37 UTC
I am trying to read the raw data from Luminex Xponent 4.1 experiments, but have bumped into some problems.

First, the file does not seem to be FCS compliant (missing $NEXTDATA keyword for single dataset experiment), which I bypass in `readFCStext` by inserting the value 0 to indicate it is a single dataset:

`if(!"$NEXTDATA" %in% names(rv)) rv <- c(rv, "$NEXTDATA" = 0)`

The problem reported in this issue arises when preparing the dataset from the raw data (integer, multisize parameters). On calling the cpp function `convertRawBites` from `readFCSdata` the following error is raised:

`Error: tinyformat: Not enough conversion specifiers in format string`

I include a [sample file](https://drive.google.com/open?id=0B_o4LwUHcbobVE5VeFNzM3pVVUU) which can be used to reproduce the issue.

**Comment by mikejiang** [comment] 2016-05-04 22:03
There are three uncommon aspects in your data :
1. missing `$NEXTDATA`
2. diverse bit widths
3. big integer of 64 bit

We can easily relax the rule to tack the first one as you've already done.
The second one was already addressed by #46. But it currently only handles the integer size of `1,2,4` bytes and thus failed on the third one. I will see what I can do.

**Comment by mikejiang** [comment] 2016-05-04 22:42
@odeleongt , Check out the latest fix from `trunk` and let me know the data looks correct.

And can you make sure if the data is actually stored in `uint_64` format for some parameters/channels? Because converting that to `double` (which is only way for R to represent your big int without third-party package) could lose precision.

**Comment by odeleongt** [comment] 2016-05-04 23:49
@mikejiang I also find odd that data should be stored in `uint_64` and, although I get data back after fixing a couple of issues, the data do not make sense. Every value is just `-2147483648`.

I'll look more into this and let you know if I find anything different. I'll try to generate some more lxbs to check if there is any difference.

Could this depend on the data capture platform? (Magpix) I'll try to get some lxbs from the Luminex 100/200 as well to check.

You'll find the changes I included in this patch [0001-Fix-cpp-errors-and-warnings.txt](https://github.com/RGLab/flowCore/files/249765/0001-Fix-cpp-errors-and-warnings.txt)

**Comment by odeleongt** [comment] 2016-05-05 17:09
It seems the Xponent software saves the raw events as a csv as well, I include it [here](https://drive.google.com/open?id=0B_o4LwUHcbobSE5vRUVMdlZ3ODA) in case it helps figure this out. I do not know if both files are supposed to contain the same information, though, and would expect the lxb file to contain more data since it somewhat tries to adhere to the FCS specification.

**Comment by raphg** [comment] 2016-05-05 18:37
@SRenan Can you help with this, as you've look at lots of Luminex data.

**Comment by mikejiang** [comment] 2016-05-06 22:35
If you look at the TEXT section of your fcs file, every single `$PnR` is recorded as value `-2147483648`. Does that mean the data was already corrupted? Can you reload it into your Xponent to double check?

**Comment by mikejiang** [comment] 2016-05-06 23:24
It turns out the negative data values were caused by `data truncation` (described [here](https://github.com/RGLab/flowCore/issues/37)). Since all your range are `-2147483648`, then the data gets truncated automatically by default. So you can simply turn off this behavior by setting `truncate_max_range = F` in `read.FCS`. 
But it is still worth to investigate why the range are negative in the first place.

**Closed** 2016-05-26 20:11 UTC
