### ISSUE TITLE
Removal of marker assignment not working properly for cytoset objects

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/flowCore#191] opened 2020-06-10 04:30 UTC
Hi @mikejiang & @jacobpwagner,

Looks like the removal of marker assignment does not work as expected for cytoset objects. See examples below:
```{r}
library(CytoExploreRData)
library(flowCore)
library(flowWorkspace)

# flowSet & cytoset
fs <- Activation
cs <- flowSet_to_cytoset(fs)

# Current marker assignments
markers <- markernames(fs)
markers

# Remove CD8 marker assignment in Alexa Fluor 488-A
markers["Alexa Fluor 488-A"] <- NA

# Update markernames in flowSet
markernames(fs) <- markers
markernames(fs)
             PE-A           7-AAD-A Alexa Fluor 405-A Alexa Fluor 430-A 
            "Va2"            "CD69"     "Hoechst-405"     "Hoechst-430" 
Alexa Fluor 647-A Alexa Fluor 700-A         APC-Cy7-A 
           "CD44"             "CD4"           "CD11c" 

# Update markernames in cytoset
markernames(cs) <- markers
markernames(cs)
Alexa Fluor 488-A              PE-A           7-AAD-A Alexa Fluor 405-A 
             "NA"             "Va2"            "CD69"     "Hoechst-405" 
Alexa Fluor 430-A Alexa Fluor 647-A Alexa Fluor 700-A         APC-Cy7-A 
    "Hoechst-430"            "CD44"             "CD4"           "CD11c" 
```

As you can see the maker is successfully removed for flowSet objects but converted to an `"NA"` character string for cytoset objects. As expected the same is observed for GatingSet objects and `flowWorkspace::markernames()`.

I am having issues compiling the latest `cytolib` so my package versions are a bit out-dated. Hopefully you encounter the same issue with latest version of `flowCore`, otherwise we can close this.

Thanks for you help!
Dillon

**Comment by jacobpwagner** [comment] 2020-06-10 09:42
Yeah, the issue is that the change of marker to NA is ignored here:
https://github.com/RGLab/flowWorkspace/blob/a76ba247fa8d962625cebe86215dbbad896cfc92/R/cytoframe.R#L458

Because the logic is assuming a string->string replacement, which is done using `flowWorkspace::setMarker`:
https://github.com/RGLab/flowWorkspace/blob/a76ba247fa8d962625cebe86215dbbad896cfc92/R/cytoframe.R#L466-L469
Which is just an `Rcpp` wrapper for `cytolib::CytoFrameView::set_marker` (which calls `cytolib::CytoFrame::set_marker`):
https://github.com/RGLab/flowWorkspace/blob/a76ba247fa8d962625cebe86215dbbad896cfc92/src/cytoframeAPI.cpp#L103-L106
Which is working on the same string->string assumption.
https://github.com/RGLab/cytolib/blob/f1ef4aabf02664f25d72c040f1dc1cc36fd2a099/src/CytoFrame.cpp#L421-L439

So, I think we'll probably just need to add a simple `remove_marker` method at the `cytolib` level that can be wrapped up when (at the R level) we see String->NA. @mikejiang, does that sound alright or was that functionality intentionally omitted?

**Comment by DillonHammill** [comment] 2020-06-10 23:42
Hmmm, I did try that @mikejiang but it does not work for flowSets. I was hoping to have a consistent method for both flowSets and cytosets. I think I might just modify the input (NA versus "") based on the class of the object at the top R level in CytoExploreR. Thanks for changing this in flowWorkspace @jacobpwagner.

**Comment by jacobpwagner** [comment] 2020-06-10 23:50
After that commit you shouldn't have to do the type check as it should now be handled by `markernames<-` for `cytoset` and `cytoframe`. So you should be able to just always use `NA` to signify drop. Let me know if that's not working for you, though, and I can take another look.

**Comment by DillonHammill** [comment] 2020-06-10 23:52
OK thanks @jacobpwagner I will try update all my packages today and give it a try. I might send through some compilation errors if I am struggling to update.

**Comment by DillonHammill** [comment] 2020-06-11 04:40
Works like a charm @jacobpwagner! Is it safe for me to use `flowWorkspace::markernames()` for flowSets/flowFrames as well? It seems to work. Otherwise I will use `flowCore::markernames()` for flowFrames/flowSets and `flowWorkspace::markernames()` for cytoframes/cytosets.

**Comment by DillonHammill** [comment] 2020-06-11 06:05
Just noting that this works well for single marker removal but `""` empty character string assignments to multiple channels are seen as an attempt to assign the same marker to multiple channels and hence produces an error. I have updated my pull request to flowWorkspace to handle the multiple empty character string case - I will try get it on par with the current flowWorkspace (I have not tried to do this before).

**Comment by jacobpwagner** [comment] 2020-06-11 06:21
Using multiple `NA` seems to work fine in my testing:
```
> library(CytoExploreRData)
> library(flowCore)
> library(flowWorkspace)
As part of improvements to flowWorkspace, some behavior of
GatingSet objects has changed. For details, please read the section
titled "The cytoframe and cytoset classes" in the package vignette:

  vignette("flowWorkspace-Introduction", "flowWorkspace")
> fs <- Activation
> cs <- flowSet_to_cytoset(fs)
> markers <- markernames(fs)
> markers
Alexa Fluor 488-A              PE-A           7-AAD-A Alexa Fluor 405-A Alexa Fluor 430-A Alexa Fluor 647-A Alexa Fluor 700-A         APC-Cy7-A 
            "CD8"             "Va2"            "CD69"     "Hoechst-405"     "Hoechst-430"            "CD44"             "CD4"           "CD11c" 
> # Remove CD8 marker assignment in Alexa Fluor 488-A
> markers[c("Alexa Fluor 488-A", "PE-A")] <- NA
> markers
Alexa Fluor 488-A              PE-A           7-AAD-A Alexa Fluor 405-A Alexa Fluor 430-A Alexa Fluor 647-A Alexa Fluor 700-A         APC-Cy7-A 
               NA                NA            "CD69"     "Hoechst-405"     "Hoechst-430"            "CD44"             "CD4"           "CD11c" 
> # Update markernames in flowSet
> markernames(fs) <- markers
> markernames(fs)
          7-AAD-A Alexa Fluor 405-A Alexa Fluor 430-A Alexa Fluor 647-A Alexa Fluor 700-A         APC-Cy7-A 
           "CD69"     "Hoechst-405"     "Hoechst-430"            "CD44"             "CD4"           "CD11c" 
> # Update markernames in cytoset
> markernames(cs) <- markers
> markernames(cs)
          7-AAD-A Alexa Fluor 405-A Alexa Fluor 430-A Alexa Fluor 647-A Alexa Fluor 700-A         APC-Cy7-A 
           "CD69"     "Hoechst-405"     "Hoechst-430"            "CD44"             "CD4"           "CD11c" 
```

Which is because the `NA`->"" conversion I just added:
https://github.com/RGLab/flowWorkspace/blob/22ea196c004a2401278cd51909c3acda13702833/R/cytoframe.R#L468-L469
Comes after this duplication check:
https://github.com/RGLab/flowWorkspace/blob/22ea196c004a2401278cd51909c3acda13702833/R/cytoframe.R#L460-L464

So, you can just use `NA` assignment for marker dropping as you were before.

**Comment by DillonHammill** [comment] 2020-06-11 07:00
Sorry @jacobpwagner, of course that is correct. I was just thinking if you wanted to retain support for empty character strings as well then the duplication needs to be addressed. But if we stick to NA no additional changes are required. I will close the PR - there is just a minor typo that can be easily fixed on your end. Thanks for your help!

**Comment by jacobpwagner** [comment] 2020-06-11 07:03
I actually merged it in with a really minor efficiency change. I think you're right that if we support dropping a single marker by empty-string assignment for `cytoframe`/`cytoset`, it makes sense for it to succeed for multiple markers.

**Comment by DillonHammill** [comment] 2020-06-11 07:11
Thanks @jacobpwagner, funny that is exactly the way I had it but separated it in case you wanted to remove it. Thanks for fixing this.

**Closed** 2020-06-11 07:11 UTC
